server:
  port: 8081

spring: #单机模式
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 1000 #最大连接数（使用负值表示没有限制）
        max-idle: 10 #最大空闲连接数
        min-idle: 5 #最小空闲连接数
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 6000ms

#spring: #集群模式
#  redis:
#    password:
#    cluster:
#      max-redirects: 3 #获取失败最大重定向次数
#      nodes:
#        - 192.168.3.43:8091
#        - 192.168.3.43:8092
#        - 192.168.3.43:8093
#    lettuce:
#      pool:
#        max-active: 1000 #最大连接数（使用负值表示没有限制）
#        max-idle: 10 #最大空闲连接数
#        min-idle: 5 #最小空闲连接数
#        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
#    timeout: 6000ms
